default_platform(:ios)

platform :ios do
  desc "Run the unit tests."
  lane :tests do
    begin
      scan(
        package_path: ".",
        scheme: "CovidCertificateSDK",
        destination: "platform=macos,arch=x86_64",
        result_bundle: true,
        output_directory: "./build/"
      )
    rescue => ex
      # Do not fail directly but mark it for later
      ENV["BUILD_RESULT"] = "FAILURE"
    end
    

    trainer(
        output_directory: "./build/",
        path: "./build/",
        fail_build: false)
    
    if ENV["BUILD_RESULT"] == "FAILURE"
      UI.crash!("Build or tests failed during xcodebuild step")
    end
  end
end
