name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: Build & Tests
    runs-on: macos-12

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Switch to Xcode 14.0.1
      run: sudo xcode-select --switch /Applications/Xcode_14.0.1.app

    - name: Fastlane
      run: fastlane tests

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@95a3aff882d4abe2838b187c66477be7fbf3ddb8
      if: always()
      with:
        files: build/*.xml

    - name: Archive logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build-test-logs
        path: build
